### ISSUE TITLE
Improve website accessibility score

### ISSUE THREAD

**Issue by ChantelleKerr** [codersforcauses/csf#108]
## Basic Information
From looking at lighthouse in the browser devtools our accessibility score is not great
We need to add aria and role attributes to elements
https://vuetifyjs.com/en/features/accessibility/

<img width="579" alt="Screen Shot 2023-07-10 at 1 31 00 pm" src="https://github.com/codersforcauses/csf/assets/45170409/2969108c-dbce-4890-8689-cd6d4533cfee">

**Comment by makon1234** [comment]
![image](https://github.com/codersforcauses/csf/assets/91424496/e90f77aa-32e0-4dc9-a615-d1e50904b7b1)

**Comment by makon1234** [comment]
Hi, score is 90
This is the main error we are getting, there is more, I didn't get all of it
Are we prepared for me to try and tweak the colours?

**Comment by ChantelleKerr** [comment]
> Hi, score is 90 This is the main error we are getting, there is more, I didn't get all of it Are we prepared for me to try and tweak the colours?

90 is fine. This is the colour they gave us so we shouldnt use something else :(
Thanks for this :D
