### ISSUE TITLE
Fix activation bug on join/create team page

### ISSUE THREAD

**Issue by Alex-Hawking** [codersforcauses/csf#176]
**This bug only seems to be present on firefox browser, not on chrome**
When the new team button is clicked on the join/create team page the elements behind it on the page also enter an activated state as per the screenshot below

![image](https://github.com/codersforcauses/csf/assets/44057725/cab1c113-e7f8-4eb9-97b2-4c729a9552de)

The activated sections turn grey, they should not be entering an activated state when the new team button is clicked.

**Comment by urwrstkn8mare** [comment]
is this an issue? i've tried it on firefox and this doesn't happen to me?

**Comment by Alex-Hawking** [comment]
> is this an issue? i've tried it on firefox and this doesn't happen to me?
> 
> <img width="1415" alt="image" src="https://github.com/codersforcauses/csf/assets/42769125/f0a964e6-7916-4b6e-b6b4-3ae676fa0521">
> 

This does happen to me as shown in the screenshot, may have just been a bug on my end? Not sure if it is worth keeping the issue open 😅

**Comment by urwrstkn8mare** [comment]
maybe try disabling extensions or smth but does seem like its on ur end

**Comment by ChantelleKerr** [comment]
I havent come across this problem

**Comment by ChantelleKerr** [comment]
is this good to remove? I cant replicate

**Comment by Alex-Hawking** [comment]
Yep go for it, seems to be fine

**Comment by RadioArsenic** [comment]
can't replicate
