### ISSUE TITLE
Update Challenge Page Description

### ISSUE THREAD

**Issue by RadioArsenic** [codersforcauses/csf#200]
The current description is based on the old Stride For Education event rather than how we handle challenges now. 
The user no longer chooses a challenge, rather challenges are used as a reference point on their dashboard to visualise their mileage. Their challenge progress resets after 14 days but we'll keep the daily kms based on 12 days to give them some leeway if they forget to log. The challenge page is just there to give them information.

**Comment by ChantelleKerr** [comment]
Hey, is this currently being worked on?

**Comment by Alex-Hawking** [comment]
> Hey, is this currently being worked on?
yep gonna finish it today 👍
