### ISSUE TITLE
Fix linting problems

### ISSUE THREAD

**Issue by aidan-0** [codersforcauses/csf#208]
Running yarn lint shows this.

<img width="778" alt="image" src="https://github.com/codersforcauses/csf/assets/127570456/2117407f-c5f4-4b2b-bb59-e625c55b2a87">

**Comment by Blizzerac** [comment]
All of these seem to have been caught and cleaned up already in the latest git pull on main, at least on my machine. Can anyone else verify?

**Comment by aidan-0** [comment]
Yep looks good to me!
