### ISSUE TITLE
Team page graph causes hamburger menu to move off screen on mobile

### ISSUE THREAD

**Issue by HuxleyBerry** [codersforcauses/csf#213]
On mobile (I'm testing with Chrome's simulator), when the graph is open, the hamburger menu moves off the right of the screen. This seems to be due to the graph itself sticking out the right of the screen

**Comment by ChantelleKerr** [comment]
<img width="375" alt="Screen Shot 2023-07-19 at 10 00 17 pm" src="https://github.com/codersforcauses/csf/assets/45170409/642f81fe-911c-430e-927a-20d3192b1764">

**Comment by HuxleyBerry** [comment]
I tried with a real phone (my iPhone), and the navbar works properly. The graph still goes a little off-screen though
