### ISSUE TITLE
fix private events can be created when user has no team_id

### ISSUE THREAD

**Issue by urwrstkn8mare** [codersforcauses/csf#217]
currently you can create private events even when you don't have a team_id. this means that after a reload it will dissapear and will never be seen again as the event is *private and has no team_id*. 

how should this work? should you not be able to create any events without joining a team or only be able to create public events without a team?

**Comment by ChantelleKerr** [comment]
Only team admins can create private events. The add event button should be hidden for users that dont have a team and are not the admin.
