### ISSUE TITLE
Create Challenge Page

### ISSUE THREAD

**Issue by ChantelleKerr** [codersforcauses/csf#22]
## Basic Information
A static Challenge page that shows a list of challenges.  This will only be 4 challenges so we dont need to store it in a database!

On notion you will find images for the challenges. You can also get more information on the current Stride For Education website.

**Comment by Alex-Hawking** [comment]
The challenges in question:

24km WOORABINDA CHALLENGE (2km daily)

60km WURRUMIYANGA CHALLENGE (5km daily)

84km GALIWIN'KU CHALLENGE (7km daily)

120km PALM ISLAND CHALLENGE (10km daily)

**Comment by Alex-Hawking** [comment]
Issue with challenge tile images having text on them, also adding title and background above challenge tiles 👍
