### ISSUE TITLE
Final clean up before handover

### ISSUE THREAD

**Issue by ChantelleKerr** [codersforcauses/csf#271]
## Basic Information

ADD TO THIS IF YOU THINK SOMETHING IS OFF

- [x] the max range for total mileage in the modal to too large maybe set min = 1, max = 50 (Alex)
- [x] Graph buttons are stuck together - check image below (fixed in subteam branch)
- [x] It looks weird on desktop we need to set max width to user dashboard and team dashboard (max width is currently too large) - check image below
- [x] Theres different text colours on team dashboard and user dashboard (Alex)
- [x] User name and Team name have different spacing - this should be consistent across the two pages 
- [x] Total mileage section UI on user and team dashboard are different
- [x] Travel method icons are different sizes on the team and user dashboards
- [x] Leaderboard section in team dashboard should display "Coming soon"
- [x] "Confirm Team delete" - has inconsistent case - check other dialogs as well (Alex)
- [x] Change avatar and change travel method has different cases on settings page (Alex)
- [ ] Could make the hover effect darker for the graph buttons
- [x] the graph has a blue line when hover but its like offset in some sections - either fix or remove. (chantelle) - removed
- [x] Total_mileage is a required field for team and user (Samit)
- [x] Spacing for graph buttons could be bigger (Alex)

<img width="1484" alt="Screen Shot 2023-07-24 at 12 34 48 pm" src="https://github.com/codersforcauses/csf/assets/45170409/12161483-9f19-4012-8e19-7dfb121e96c9">

**Comment by Alex-Hawking** [comment]
I made a branch for people to work on these points, put your name in brackets next to what you are working on to avoid conflicts
