### ISSUE TITLE
Create subteam endpoint

### ISSUE THREAD

**Issue by RadioArsenic** [codersforcauses/csf#54]
# Prerequisite
#40 Team API endpoint

# Information
Create a new API endpoint for the "Subteam" db table using the Django REST framework. This task is split into multiple small parts that each team member can tackle! It should be under the folder server/api/subteam

1. Create Subteam Model in `models.py`
2. Create Views in `views.py`
It should have views for the following operations:
- create a new subteam
- read/get details of subteam
- update details of the subteam
- delete subteam, be careful with this we dont want to lose existing data if the subteam id is a FK in another table
3.  Add url patterns to `urls.py`
4.  Register the app for the admin

You will be required to research how to complete this task!

TIP: You can use postman to test your endpoints!

Model data:
- subteam_id
- name
- team_id

**Comment by ChantelleKerr** [comment]
Team API is in main now, Please merge main into this branch :)
