### ISSUE TITLE
User settings page

### ISSUE THREAD

**Issue by ChantelleKerr** [codersforcauses/csf#79]
## Basic Information
Be able to update account information
- username
- first name
- last name
- email
- password
- travel method
- avatar

You will also need to design this page

**Comment by ChantelleKerr** [comment]
I would put a settings cog icon on the user dashboard page at the end of the welcome message @K-Straiton Theres already a view created for settings page in main

**Comment by RadioArsenic** [comment]
It would also make sense for the user's name in the navbar to link to the settings page so do that too please :)
