### ISSUE TITLE
Create navigation bar

### ISSUE THREAD

**Issue by ChantelleKerr** [codersforcauses/csf#9]
A responsive top navigation bar (must work for both desktop and mobile) that will be displayed across all pages

The CSF logo should be displayed on the top left
It should contain the following links:
- About us
- Challenges
- Events
- Dashboard
- Team

Sign up and login buttons

TIP: Vuetify has some good components that will help with this task!

**Comment by OsafAliSayed** [comment]
hi I would like to work on this issue
