### ISSUE TITLE
Protect Endpoints

### ISSUE THREAD

**Issue by ChantelleKerr** [codersforcauses/csf#96]
When you login as a user a JWT access token returns, we need to use that token when making requests to:

Event
- update
- delete
Note:
- We need only public events to be return for unauthenticated users.
- If the user has a team they can only see events for their team.

Team
- Create Team - only for authenticated user
- Update team - Only admin of team
- delete team - Only admin of team
-Note: users that do not have a team can join a team 

Mileage
- Create mileage - only for authenticated users
- Get  mileage - only for authenticated user 

Subteam
- Create - only admin of the team can create
- edit - only admin
- delete only admin of team

**Comment by benvarian** [comment]
for event -> update and del, what exactly do you want me to limit?

**Comment by ChantelleKerr** [comment]
> for event -> update and del, what exactly do you want me to limit?

only authenicated users can update, delete and create. Only team admins can update and delete/archive their events
